version: "3"

services:
  main-db:
    image: postgres
    ports:
      - "5468:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - main-db-data:/var/lib/postgresql/data

volumes:
  main-db-data:
